# Generated by Django 2.1.7 on 2021-05-25 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lession_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(verbose_name='chapter no')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='videos')),
                ('ppt', models.FileField(blank=True, upload_to='', verbose_name='presentations')),
                ('notes', models.FileField(blank=True, upload_to='', verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Subject Image')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('standerd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='curriculam.Standard')),
            ],
        ),
        migrations.AddField(
            model_name='lession',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculam.Standard'),
        ),
        migrations.AddField(
            model_name='lession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessions', to='curriculam.Subject'),
        ),
    ]
