# Generated by Django 2.1.7 on 2021-05-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lession',
            old_name='standard',
            new_name='Standard',
        ),
        migrations.RenameField(
            model_name='lession',
            old_name='lession_id',
            new_name='lesson_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='standerd',
            new_name='standard',
        ),
        migrations.RemoveField(
            model_name='lession',
            name='notes',
        ),
        migrations.AddField(
            model_name='lession',
            name='Notes',
            field=models.FileField(blank=True, upload_to='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='lession',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='lession',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Chapter no.'),
        ),
        migrations.AlterField(
            model_name='lession',
            name='ppt',
            field=models.FileField(blank=True, upload_to='', verbose_name='Presentations'),
        ),
        migrations.AlterField(
            model_name='lession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculam.Subject'),
        ),
        migrations.AlterField(
            model_name='lession',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Video'),
        ),
    ]
