# Generated by Django 2.1.7 on 2021-05-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculam', '0002_auto_20210526_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lession',
            old_name='lesson_id',
            new_name='lession_id',
        ),
        migrations.AlterField(
            model_name='lession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessions', to='curriculam.Subject'),
        ),
    ]
